# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 19:50
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunnyStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('short_description', models.CharField(max_length=500)),
                ('story_image', models.ImageField(upload_to='uploads/success_stories_icons/')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 8, 5, 19, 50, 10, 568423, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='FunStorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 8, 5, 19, 50, 10, 568423, tzinfo=utc))),
                ('funny_story', models.ManyToManyField(blank=True, related_name='tags', to='funny_stories.FunnyStories')),
            ],
        ),
    ]
