# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-23 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('funny_stories', '0012_auto_20190322_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnystories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 21, 12, 52, 71334, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='funstortag',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 21, 12, 52, 71334, tzinfo=utc)),
        ),
    ]
