# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-22 10:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('funny_stories', '0022_auto_20191020_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnystories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 10, 42, 58, 157972, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='funstortag',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 10, 42, 58, 159304, tzinfo=utc)),
        ),
    ]
