# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-15 12:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('funny_stories', '0024_auto_20191028_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnystories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 12, 3, 39, 277887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='funstortag',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 12, 3, 39, 278585, tzinfo=utc)),
        ),
    ]
