# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-14 17:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='success_stories',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='success_stories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 14, 17, 38, 58, 954707, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 14, 17, 38, 58, 954707, tzinfo=utc)),
        ),
    ]
