# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-14 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0003_auto_20180714_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success_stories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 14, 17, 43, 24, 249302, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 14, 17, 43, 24, 249302, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='success_story',
            field=models.ManyToManyField(blank=True, related_name='tags', to='success_stories.Success_stories'),
        ),
    ]
