# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-14 19:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0004_auto_20180714_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success_stories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 14, 19, 3, 8, 940997, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 14, 19, 3, 8, 940997, tzinfo=utc)),
        ),
    ]
