# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-14 19:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0006_auto_20180714_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success_stories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 14, 19, 6, 10, 409811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='success_stories',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 14, 19, 6, 10, 409811, tzinfo=utc)),
        ),
    ]
