# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0007_auto_20180714_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='success_stories',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='success_stories',
            name='short_description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='success_stories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 18, 21, 37, 325074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 18, 21, 37, 325074, tzinfo=utc)),
        ),
    ]
