# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0008_auto_20180722_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='success_stories',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/success_stories/<function get_self_pk at 0x03916390>'),
        ),
        migrations.AlterField(
            model_name='success_stories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 18, 51, 35, 315079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 18, 51, 35, 316079, tzinfo=utc)),
        ),
    ]
