# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 17:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0021_auto_20180729_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success_stories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 29, 17, 2, 45, 337220, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 29, 17, 2, 45, 337220, tzinfo=utc)),
        ),
    ]
