# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-04 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0046_auto_20180801_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='success_stories',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='success_stories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 4, 19, 15, 3, 614085, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 4, 19, 15, 3, 614085, tzinfo=utc)),
        ),
    ]
