# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 19:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0047_auto_20180804_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success_stories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 5, 19, 50, 10, 287623, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 5, 19, 50, 10, 287623, tzinfo=utc)),
        ),
    ]
