# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-19 21:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0048_auto_20180805_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success_stories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 21, 4, 41, 576461, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 21, 4, 41, 577461, tzinfo=utc)),
        ),
    ]
