# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 21:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0049_auto_20180819_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success_stories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 21, 51, 38, 40963, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 21, 51, 38, 40963, tzinfo=utc)),
        ),
    ]
