# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-22 04:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0068_auto_20190421_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success_stories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 4, 6, 52, 656863, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 4, 6, 52, 656863, tzinfo=utc)),
        ),
    ]
