# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-22 10:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0069_auto_20191020_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success_stories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 10, 42, 58, 37482, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 10, 42, 58, 38565, tzinfo=utc)),
        ),
    ]
