# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-28 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0070_auto_20191022_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success_stories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 12, 5, 43, 106517, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 12, 5, 43, 107681, tzinfo=utc)),
        ),
    ]
