# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-24 02:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0071_auto_20190422_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success_stories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 2, 0, 20, 254079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 2, 0, 20, 254079, tzinfo=utc)),
        ),
    ]
