# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-15 12:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0075_auto_20191115_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success_stories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 12, 23, 42, 891599, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 12, 23, 42, 892410, tzinfo=utc)),
        ),
    ]
