# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-30 20:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anim_site_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_page',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 30, 20, 57, 26, 977326, tzinfo=utc)),
        ),
    ]
