# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-23 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anim_site_main', '0010_auto_20190322_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_page',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 21, 12, 51, 976334, tzinfo=utc)),
        ),
    ]
