# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-26 04:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anim_site_main', '0012_auto_20190325_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_page',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 4, 27, 3, 931974, tzinfo=utc)),
        ),
    ]
