# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='country',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
