# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180730_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='state',
            field=models.CharField(blank=True, choices=[('--', 'Not From States'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California')], default='--', max_length=30),
        ),
    ]
