# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_appuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='birth_date',
            field=models.CharField(default='some string', max_length=300),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='state',
            field=models.CharField(blank=True, choices=[('NAN', 'Not From States'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California')], default='NAN', max_length=25),
        ),
    ]
