# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 23:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180801_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 1, 23, 37, 43, 102376, tzinfo=utc)),
        ),
    ]
