# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 19:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180804_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 5, 19, 50, 10, 568423, tzinfo=utc)),
        ),
    ]
