# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-19 21:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180805_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 19, 21, 4, 41, 703468, tzinfo=utc)),
        ),
    ]
