# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 21:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180819_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 20, 21, 51, 38, 165763, tzinfo=utc)),
        ),
    ]
