# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-30 20:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180820_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 30, 20, 57, 27, 119726, tzinfo=utc)),
        ),
    ]
