# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-02 17:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180830_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='department',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 2, 17, 52, 15, 615286, tzinfo=utc)),
        ),
    ]
