# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 03:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20190318_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 19, 3, 40, 34, 222042, tzinfo=utc)),
        ),
    ]
