# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-23 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20190322_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 23, 21, 12, 52, 61334, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
