# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-26 04:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20190323_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 26, 4, 15, 51, 594069, tzinfo=utc)),
        ),
    ]
