# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-05 04:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20190402_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 5, 4, 32, 38, 427097, tzinfo=utc)),
        ),
    ]
