# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-26 01:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20190404_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='view_count_expire',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 26, 1, 30, 37, 158409, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 26, 1, 30, 37, 158409, tzinfo=utc)),
        ),
    ]
