# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-22 04:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20190421_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='view_count_expire',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 22, 4, 18, 12, 45414, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 22, 4, 18, 12, 45414, tzinfo=utc)),
        ),
    ]
