# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-28 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20191022_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 28, 12, 5, 43, 160561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='view_count_expire',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 28, 12, 5, 43, 160444, tzinfo=utc)),
        ),
    ]
