# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-24 02:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20190422_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='view_count_expire',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 24, 2, 0, 20, 364079, tzinfo=utc)),
        ),
    ]
