# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-15 12:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20191115_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 15, 12, 15, 2, 235237, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='view_count_expire',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 15, 12, 15, 2, 235124, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_advertiset',
            field=models.BooleanField(blank=True, default=False)
        ),
    ]
