# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-15 12:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20191115_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_advertiset',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 15, 12, 21, 37, 28472, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='view_count_expire',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 15, 12, 21, 37, 28370, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_advertiser',
            field=models.BooleanField(blank=True, default=False)
        ),
    ]
