# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-15 12:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20191115_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 15, 12, 23, 42, 941727, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='view_count_expire',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 15, 12, 23, 42, 941618, tzinfo=utc)),
        ),
    ]
