# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-19 21:04
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('short_description', models.CharField(max_length=500)),
                ('story_image', models.ImageField(blank=True, upload_to='uploads/success_stories_icons/')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 8, 19, 21, 4, 41, 712469, tzinfo=utc))),
            ],
        ),
    ]
