# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-23 03:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190318_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 3, 7, 40, 851704, tzinfo=utc)),
        ),
    ]
