# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-30 20:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180830_1657'),
        ('ad_donation', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 8, 30, 20, 57, 27, 119726, tzinfo=utc))),
                ('who_donated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AppUser')),
            ],
        ),
    ]
