# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 03:20
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ad_donation', '0006_auto_20190317_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_for_donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('short_description', models.CharField(max_length=500)),
                ('project_image', models.ImageField(upload_to='uploads/project_for_donations/')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 3, 19, 3, 20, 23, 282545, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='donations',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 3, 20, 23, 282545, tzinfo=utc)),
        ),
    ]
