# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 03:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ad_donation', '0008_auto_20190318_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_for_donations',
            name='amount_donated',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project_for_donations',
            name='amount_required',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='donations',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 3, 40, 34, 222042, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project_for_donations',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 3, 40, 34, 222042, tzinfo=utc)),
        ),
    ]
