# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-23 03:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ad_donation', '0010_auto_20190318_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_for_donations',
            name='percentage_donated',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='donations',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 3, 7, 40, 841704, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project_for_donations',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 3, 7, 40, 841704, tzinfo=utc)),
        ),
    ]
