# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-05 04:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ad_donation', '0018_auto_20190402_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donations',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 4, 32, 38, 429097, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project_for_donations',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 4, 32, 38, 428097, tzinfo=utc)),
        ),
    ]
