# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-20 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ad_donation', '0020_auto_20190425_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 11, 24, 15, 525, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project_for_donations',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 11, 24, 14, 999701, tzinfo=utc)),
        ),
    ]
